Task.create(title: "Finish APLYiD test", body:"Try to finish it by Sunday.")
Task.create(title: "Learn Rails", body:"Watch online courses.")
Task.create(title: "Learn Vuejs", body:"Vuejs docs are the best resources to learn the framework.")
Task.create(title: "Go to supermarket", body:"Buy Milk, Eggs and Bread!")
Task.create(title: "Go for run")
